<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configurations>Debug;Release</Configurations>
        <LangVersion>latest</LangVersion>
        <VersionPrefix>0.1.8</VersionPrefix>
        <Optimize>True</Optimize>
        <DebugType>Portable</DebugType>
        <PreserveCompilationContext>false</PreserveCompilationContext>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>https://thesilvercraft.github.io/cscore/</PackageProjectUrl>
        <RepositoryUrl>https://github.com/thesilvercraft/cscore</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>cscore;audio;linux;</PackageTags>
        <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
        <AnalysisLevel>latest-all</AnalysisLevel>
        <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <Deterministic>true</Deterministic>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageReleaseNotes>Links and rename openmpt package</PackageReleaseNotes>
        <PackageIcon>cscore-square-notext.png</PackageIcon>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <Optimize>False</Optimize>
    </PropertyGroup>
    <ItemGroup>
        <None Include="..\cscore-square-notext.png" Pack="true" PackagePath="\"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="DotNet.ReproducibleBuilds" Version="1.1.1" PrivateAssets="All" />
    </ItemGroup>
</Project>