<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../SilverCraft.CSCore.targets" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>openmpt support for SilverCraft.CSCore</Description>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <AssemblyName>SilverCraft.CSCore.OpenMPT</AssemblyName>
    <RootNamespace>SilverCraft.CSCore.OpenMPT</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SilverCraft.CSCore\SilverCraft.CSCore.csproj" />
    <PackageReference Include="SilverAudioPlayer.Shared" Version="7.4.2" />
  </ItemGroup>
  <ItemGroup>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SilverCraft.CSCore.NativeLibraryResolver\SilverCraft.CSCore.NativeLibraryResolver.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"/>
  </ItemGroup>
</Project>