<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="../SilverCraft.CSCore.targets" />
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Description>vgmstream support for SilverCraft.CSCore</Description>
        <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
        <IncludeSymbols>True</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SilverCraft.CSCore\SilverCraft.CSCore.csproj" />
    </ItemGroup>
    <ItemGroup>
        <None Update="README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>
</Project>
