using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;


namespace SilverCraft.CSCore.NativeLibraryResolver;

/// <summary>
/// A sample source generator that creates a custom report based on class properties. The target class should be annotated with the 'Generators.ReportAttribute' attribute.
/// When using the source code as a baseline, an incremental source generator is preferable because it reduces the performance overhead.
/// </summary>
[Generator]
public class SourceGeneratorWithAttributes : IIncrementalGenerator
{
    private const string Namespace = "Generators";
    private const string AttributeName = "DllImportResolverAttribute";

    private const string AttributeSourceCode = $$"""
                                                 // <auto-generated/>
                                                 // a generator wrote this file, don't judge it that hard
                                                 namespace {{Namespace}}
                                                 {
                                                     [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
                                                     public class {{AttributeName}} : System.Attribute
                                                     {
                                                         public string LibraryName { get; }
                                                         public string DllName { get; }
                                                         public string[] WindowsDlls { get; set; } = [];
                                                         public string[] LinuxDlls { get; set; } = [];
                                                         public string[] MacOsDlls { get; set; } = [];
                                                         public string LinuxInstructions { get; set; } = "";
                                                         public string GenericInstructionsStart { get; set; } = "";
                                                         public string GenericInstructionsWindowsEnd { get; set; } = "";
                                                         public string GenericInstructionsLinuxEnd { get; set; } = "";

                                                         public {{AttributeName}}(string libraryName, string dllName)
                                                         {
                                                             LibraryName = libraryName;
                                                             DllName = dllName;
                                                         }
                                                     }
                                                 }
                                                 """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Add the marker attribute to the compilation.
        context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
            "DllImportResolverAttribute.g.cs",
            SourceText.From(AttributeSourceCode, Encoding.UTF8)));

        // Filter classes annotated with the [Report] attribute. Only filtered Syntax Nodes can trigger code generation.
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is ClassDeclarationSyntax,
                (ctx, _) => GetClassDeclarationForSourceGen(ctx))
            .Where(t => t.reportAttributeFound)
            .Select((t, _) => t.Item1);

        // Generate the source code.
        context.RegisterSourceOutput(context.CompilationProvider.Combine(provider.Collect()),
            ((ctx, t) => GenerateCode(ctx, t.Left, t.Right)));
    }

    /// <summary>
    /// Checks whether the Node is annotated with the [Report] attribute and maps syntax context to the specific node type (ClassDeclarationSyntax).
    /// </summary>
    /// <param name="context">Syntax context, based on CreateSyntaxProvider predicate</param>
    /// <returns>The specific cast and whether the attribute was found.</returns>
    private static (ClassDeclarationSyntax, bool reportAttributeFound) GetClassDeclarationForSourceGen(
        GeneratorSyntaxContext context)
    {
        var classDeclarationSyntax = (ClassDeclarationSyntax)context.Node;

        // Go through all attributes of the class.
        foreach (var attributeSyntax in classDeclarationSyntax.AttributeLists.SelectMany(attributeListSyntax => attributeListSyntax.Attributes))
        {
            if (ModelExtensions.GetSymbolInfo(context.SemanticModel, attributeSyntax).Symbol is not IMethodSymbol attributeSymbol)
                continue; // if we can't get the symbol, ignore it

            var attributeName = attributeSymbol.ContainingType.ToDisplayString();

            // Check the full name of the [Report] attribute.
            if (attributeName == $"{Namespace}.{AttributeName}")
                return (classDeclarationSyntax, true);
        }
        

        return (classDeclarationSyntax, false);
    }

    private void GenerateCode(SourceProductionContext context, Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> classDeclarations)
    {
        var attributeSymbol = compilation.GetTypeByMetadataName($"{Namespace}.{AttributeName}");
        if (attributeSymbol is null) return;

        foreach (var classDeclarationSyntax in classDeclarations)
        {
            var semanticModel = compilation.GetSemanticModel(classDeclarationSyntax.SyntaxTree);

            if (ModelExtensions.GetDeclaredSymbol(semanticModel, classDeclarationSyntax) is not INamedTypeSymbol classSymbol)
                continue;

            var attributeData = classSymbol.GetAttributes()
                .FirstOrDefault(ad => SymbolEqualityComparer.Default.Equals(ad.AttributeClass, attributeSymbol));

            if (attributeData is null) continue;

            string namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace
                ? string.Empty
                : classSymbol.ContainingNamespace.ToDisplayString();

            string className = classSymbol.Name;

            // Positional constructor arguments
            string libraryName = attributeData.ConstructorArguments.Length > 0
                ? attributeData.ConstructorArguments[0].Value?.ToString() ?? ""
                : "";

            string dllName = attributeData.ConstructorArguments.Length > 1
                ? attributeData.ConstructorArguments[1].Value?.ToString() ?? ""
                : "";

            // Named arguments
            var namedArgs = attributeData.NamedArguments.ToDictionary(kv => kv.Key, kv => kv.Value);

            string[] windowsDlls = GetStringArrayArgument(namedArgs, "WindowsDlls");
            string[] linuxDlls = GetStringArrayArgument(namedArgs, "LinuxDlls");
            string[] macOsDlls = GetStringArrayArgument(namedArgs, "MacOsDlls");

            string linuxInstructions = GetStringArgument(namedArgs, "LinuxInstructions");
            string genericInstructionsStart = GetStringArgument(namedArgs, "GenericInstructionsStart");
            string genericInstructionsWindowsEnd = GetStringArgument(namedArgs, "GenericInstructionsWindowsEnd");
            string genericInstructionsLinuxEnd = GetStringArgument(namedArgs, "GenericInstructionsLinuxEnd");
            string startInstructionCode = string.IsNullOrWhiteSpace(genericInstructionsStart)
                ? ""
                : $"Console.Error.WriteLine({SymbolDisplay.FormatLiteral(genericInstructionsStart, true)}, os, cpu);";
            string winEndLiteral = SymbolDisplay.FormatLiteral(genericInstructionsWindowsEnd, true);
            string linuxEndLiteral = SymbolDisplay.FormatLiteral(genericInstructionsLinuxEnd, true);

            string endInstructionCode;
            if (!string.IsNullOrWhiteSpace(genericInstructionsWindowsEnd) || !string.IsNullOrWhiteSpace(genericInstructionsLinuxEnd))
            {
                bool usesPathWin = genericInstructionsWindowsEnd.Contains("{0}");
                bool usesPathLinux = genericInstructionsLinuxEnd.Contains("{0}");

                if (usesPathWin || usesPathLinux)
                {
                    endInstructionCode = $"""
                                           Console.Error.WriteLine(OperatingSystem.IsWindows()
                                                   ? {winEndLiteral}
                                                   : {linuxEndLiteral}, string.IsNullOrEmpty(assembly?.Location) ? AppContext.BaseDirectory : Path.GetDirectoryName(assembly.Location)!);
                                           """;
                }
                else
                {
                    endInstructionCode = $"""
                                           Console.Error.WriteLine(OperatingSystem.IsWindows()
                                                   ? {winEndLiteral}
                                                   : {linuxEndLiteral});
                                           """;
                }
            }
            else
            {
                endInstructionCode = "";
            }
            string code = $$"""
                // <auto-generated/>
                // a generator wrote this file, don't judge it that hard
                #nullable enable

                using System;
                using System.IO;
                using System.Reflection;
                using System.Runtime.InteropServices;

                {{(string.IsNullOrEmpty(namespaceName) ? "" : $"namespace {namespaceName};")}}

                partial class {{className}}
                {
                    public static IntPtr DllImportResolver(string libraryName, Assembly assembly, DllImportSearchPath? searchPath)
                    {
                        if (libraryName != {{SymbolDisplay.FormatLiteral(dllName, true)}}) return IntPtr.Zero;
                        string[] candidates = OperatingSystem.IsWindows() switch
                        {
                            true => {{FormatStringArrayLiteral(windowsDlls)}},
                            false when OperatingSystem.IsMacOS() => {{FormatStringArrayLiteral(macOsDlls)}},
                            _ => {{FormatStringArrayLiteral(linuxDlls)}}
                        };
                        foreach (var candidate in candidates)
                        {
                            if (NativeLibrary.TryLoad(candidate, assembly, searchPath, out IntPtr handle))
                            {
                                return handle;
                            }
                        }
                        const string unknown = "unknown";
                        var os = unknown;
                        if (OperatingSystem.IsWindows()) os = "windows";
                        else if (OperatingSystem.IsMacOS()) os = "macos";
                        else if (OperatingSystem.IsLinux()) os = "linux";
                        var cpu = RuntimeInformation.ProcessArchitecture switch
                        {
                            Architecture.X64 => "x86_64",
                            Architecture.Arm64 => "aarch64",
                            _ => unknown
                        };
                        Console.Error.WriteLine("Could not find " + {{SymbolDisplay.FormatLiteral(libraryName, true)}});
                        if (OperatingSystem.IsLinux())
                        {
                            Console.Error.WriteLine({{SymbolDisplay.FormatLiteral(linuxInstructions, true)}});
                        }
                        if (os == unknown || cpu == unknown) return IntPtr.Zero;
                        {{startInstructionCode}}
                        {{endInstructionCode}}
                        return IntPtr.Zero;
                    }
                }
                """;

            context.AddSource($"{className}.DllImportResolver.g.cs", SourceText.From(code, Encoding.UTF8));
        }
    }

    private static string GetStringArgument(Dictionary<string, TypedConstant> namedArgs, string key)
    {
        return namedArgs.TryGetValue(key, out var constant) && constant.Value is string val ? val : string.Empty;
    }

    private static string[] GetStringArrayArgument(Dictionary<string, TypedConstant> namedArgs, string key)
    {
        if (namedArgs.TryGetValue(key, out var constant) && !constant.IsNull && constant.Kind == TypedConstantKind.Array)
        {
            return constant.Values
                .Select(v => v.Value?.ToString() ?? string.Empty)
                .ToArray();
        }
        return Array.Empty<string>();
    }

    private static string FormatStringArrayLiteral(string[] items)
    {
        if (items.Length == 0) return "[]";
        var literals = items.Select(i => SymbolDisplay.FormatLiteral(i, true));
        return $"[{string.Join<string>(", ", literals)}]";
    }
}